import type { Metadata } from "next";
import { inter, shadowsIntoLight } from '@/app/ui/fonts';
import '@/app/ui/global.css';
import TopNav from '@/app/ui/home/top-nav';
export const metadata: Metadata = {
  title: {
    template: '%s',
    default: 'Home',
  },
  description: "Generated by create next app",
  icons: {
    icon:'./icon.ico',
  }
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <TopNav />
      {children}
      </body>
    </html>
  );
}
