import { inter, shadowsIntoLight } from '@/app/ui/fonts';
import '@/app/ui/global.css';
import type { Metadata } from "next";
import TopNav from '@/app/ui/home/top-nav';
import 'katex/dist/katex.min.css'

export const metadata: Metadata = {
  title: 'Home', // Ensure this is a string
  description: "Generated by create next app",
  icons: {
    icon: '/web_images/icon.ico',
  }
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`bg-fixed bg-cover ${inter.className}`}>
        <TopNav />
        {children}
      </body>
    </html>
  );
}
